name: Generate Snake Animation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Esegui il workflow ogni giorno a mezzanotte

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: dist/github-contribution-grid-snake.svg

      - name: Push generated Snake
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true
